#!/bin/bash

# Template in /usr/share/pandoc/data/templates/

# File
F="$1"
OUT="${F%.md}.pdf"

# Open pdf

#pandoc -f markdown -t latex -o $OUT $F
#pandoc --indented-code-classes=python --highlight-style=tango -f markdown -t latex -o $OUT $F
pandoc --template notetaking.latex --indented-code-classes=python --highlight-style=tango -f markdown -t latex -o $OUT $F
#xdg-open $OUT & disown
mupdf $OUT & disown

fileTime=`stat -c %X $F`

# While file is open
while :
do
    # Get latest write time
    newTime=`stat -c %X $F`

    # Compare write time to last write time
    if [[ "$fileTime" -ne "$newTime" ]]
    then
        fileTime=$newTime
        
        # If modified regen pdf
        #pandoc --indented-code-classes=python --highlight-style=tango -f markdown -t latex -o $OUT $F
        pandoc --template notetaking.latex --indented-code-classes=python --highlight-style=tango -f markdown -t latex -o $OUT $F
        # Update pdf
        pkill -SIGHUP mupdf
    fi

    # Check file isnt closed
    if ! [[ `lsof +D ./ | grep $F` ]]
    then
        break
    fi

    sleep 1 
done    
